### ISSUE TITLE
Question about the embeddings

### ISSUE THREAD

**Issue by GriesserP** [baidu-research/vidpress-sports#4]
Hello,
Thank you very much for your contributionS and the realease of the embeddings.
I have some questions about them. 
- Are the embeddings of size 8576 a concatenation of tpn_50, gta,vtn,ircsn,i3d-slow in this order ? So if I retrieve the first 2048 dimension ,do I end up with the tpn_50 features ?
- If yes to the previous question, we don't have access to the tpn_101 featuers right ?
- I am in fact trying to reproduce your idea of feature combination for an other dataset of football videos and I think that the process isn't trivial at all since it requires to understand and adapt the code of 5 other papers (one for each tpn,gta,vta,slowfast and ircsn). So could you provide the code to reproduce these embeddings ? 

Cordially, Paul

**Comment by GriesserP** [comment]
Ok I understand, thank you for the help!

**Comment by yur1xpp** [comment]
Hi @kl2005ad, does the plan of not releasing the code publicly still holds for now? Will the code be open eventually?

Thanks!

**Comment by kl2005ad** [comment]
@yur1xpp We still cannot release the code. Unfortunately, we cannot make any promises about when to release the code. Thanks for your interest.
